spring:
  cloud:
    gateway:
     discovery:
      locator: 
        enabled: true
     
      routes:
      - id: currency-calculator
        uri: lb://currency-calculator
        predicates:
        - Path=/currency-calculator/**
        
      routes:
      - id: currency-conversion
        uri: lb://currency-conversion
        predicates:
        - Path=/currency-conversion/**
        
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.100:9411/
    
    
