   
spring:
  cloud:
    gateway:
      metrics:
        enabled: true

      
      routes:
      
      - id: currency-calculator
        uri: currency-calculator
        predicates:
        - Path: /currency-calculator-feign/**        