   
spring:
  cloud:
    gateway:
      metrics:
        enabled: true

      
      routes:
      - id: currency-conversion
        uri: lb://currency-conversion
        predicates:
        - Path=/currency-conversion/**