spring:
  cloud:
    gateway:
      metrics:
        enabled: true

      
      routes:    
      - id: currency-conversion
        uri: http://localhost:8200/
        predicates:
        - Path=/currency-conversion/retrieve/**