spring:
  cloud:
    gateway:
      metrics:
        enabled: true

      
      routes:
      
      - id: currency-conversion
        uri: currency-conversion
        predicates:
        - Path=/currency-conversion/retrieve/**