spring:
  cloud:
    gateway:
      metrics:
        enabled: true

      
      routes:    
      - id: conversion
        uri: localhost:8200
        predicates:
        - Path=/currency-conversion/retrieve/**