spring:
  cloud:
    gateway:
      metrics:
        enabled: true

      
      routes:    
      - id: conversion
        uri: currency-conversion
        predicates:
        - Path=/currency-conversion/retrieve/**