spring:
  application:
    name: currency-conversion
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.100:9411/
  rabbitmq:
    host: 192.168.99.100
    port: 5672
  cloud:
    bus:
      enabled: true
      destination: configXchangebus
  mvc:
   view:
     suffix: .html
     prefix: /
        
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:currencyConversion;DB_CLOSE_DELAY=-1
    username: sas
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop
        
management:
 endpoints:
    web:
      exposure:
        include: '*'
             
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka
  #    defaultZone: http://192.168.99.100:8761/eureka
      
logging:
  pattern:
    level: "[%X{X-B3-TraceId} : %X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"