--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: zuulapigateway
    version: v1
  name: zuulapigateway
spec: 
  ports: 
    - 
      name: http
      port: 8686
      targetPort: 9000
  selector: 
    app: zuulapigateway
    version: v1
  type: NodePort