spring:
  cloud:
    config:
      server:
        git:
          uri: C:\work\microservices_traininig
          skipSslValidation: true

 

            application:    name: cloud-config
    
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888