server:
  port: 8686

spring:
  application:
    name: zuul-apigateway

  zipkin:
    base-url: http://192.168.99.101:9411/
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  

zuul:
  routes: 
    currency-conversion:
      path: /currency-conversion/retrieve/**

  
management:
  endpoints:
    web:
      exposure:
        include: '*'
             
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
logging:
  pattern:
    level: "[%X{X-B3-TraceId} : %X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"