server:
  port: 8686

spring:
  application:
    name: zuul-apigateway

  zipkin:
    base-url: http://192.168.99.101:9411/
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  

zuul:
  routes: 
    currency-conversion:
      path: /currency-conversion/retrieve/**
  host:
    socket-timeout-millis: 3000  
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
             
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${zuul-apigateway.eureka.url:http://192.168.99.101:8761/eureka}