server:
  port: 8686

spring:
  application:
    name: zuul-apigateway

  zipkin:
    base-url:  ${zuul-apigateway.zipkin.url:http://zipkin:9411/}
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  

zuul:
  routes: 
    currency-conversion:
      path: /currency-conversion/retrieve/**
  
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
             
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${zuul-apigateway.eureka.client.service-registry-url:http://eureka-1:8761/eureka} 