server:
  port: 8089
  
spring:
  application:
    name: cloud-apigateway  
  
  cloud:
    gateway:
      httpclient:
        pool:
          acquire-timeout: 6000
          max-connections: 10000
        
      discovery:
        locator:
          enabled: true         

  zipkin:
    base-url: http://192.168.99.100:9411/
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    
            
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
 