server:
  port: 8089
  
spring:
  application:
    name: cloud-apigateway  
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      
    bus:
      enabled: true
      destination: configXchangebus
      
  zipkin:
    base-url: http://192.168.99.100:9411/
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  rabbitmq:
    host: 192.168.99.100
    port: 5672
  
   
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    
            
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
 #      defaultZone: http://192.168.99.100:8761/eureka
        
logging:
  pattern:
    level: "[%X{X-B3-TraceId} : %X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"